$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'ProcessArguments.ps1')
$root=[IO.Path]::GetFullPath((Split-Path -Parent $PSScriptRoot));$artifact=Join-Path $root ('artifacts\agent-scaling-'+(Get-Date -Format 'yyyyMMdd-HHmmss-fff'));$null=New-Item -ItemType Directory -Path $artifact
$results=@()
foreach($actors in @(0,1,5,10)){
  $serverDir=Join-Path $artifact "server-$actors";$null=New-Item -ItemType Directory -Path $serverDir;'eula=true'|Set-Content (Join-Path $serverDir 'eula.txt')
  @('server-ip=127.0.0.1','server-port=0','online-mode=false','level-type=minecraft:flat','generate-structures=false','view-distance=5','simulation-distance=5')|Set-Content (Join-Path $serverDir 'server.properties')
  $info=[Diagnostics.ProcessStartInfo]::new();$info.FileName=(Join-Path $root 'gradlew.bat');$info.WorkingDirectory=$root;$info.UseShellExecute=$false;$info.CreateNoWindow=$true;$info.WindowStyle=[Diagnostics.ProcessWindowStyle]::Hidden;$info.RedirectStandardOutput=$true;$info.RedirectStandardError=$true
  Set-ProcessArguments $info @('--no-daemon','runPersistenceServer',"-PjevcraftPersistenceDir=$serverDir",'-PjevcraftPersistencePhase=benchmark',"-PjevcraftBenchmarkActors=$actors")
  $process=[Diagnostics.Process]::new();$process.StartInfo=$info;$null=$process.Start();$stdout=$process.StandardOutput.ReadToEndAsync();$stderr=$process.StandardError.ReadToEndAsync()
  try{$deadline=[DateTime]::UtcNow.AddSeconds(240);$log=Join-Path $serverDir 'logs\latest.log';while([DateTime]::UtcNow -lt $deadline){if($process.HasExited){break};if((Test-Path $log)-and((Get-Content $log -Raw)-match 'AGENT_SCALE_PASS')){break};Start-Sleep -Milliseconds 500};if(!(Test-Path $log)){throw "$actors-agent log missing"};$text=Get-Content $log -Raw;if($text-notmatch 'AGENT_SCALE_PASS actors=(\d+) ticks=400 minimumEntityTicks=(\d+) tickets=(\d+) elapsedMs=(\d+) wallMspt=([0-9.]+) serverMspt=([0-9.]+)'){throw "$actors-agent benchmark marker missing"};if(!$process.WaitForExit(30000)){throw "$actors-agent server did not stop itself"};Copy-Item $log (Join-Path $artifact "$actors-latest.log");if($process.ExitCode-ne 0){throw "$actors-agent server exited $($process.ExitCode)"};$results+=@{actors=[int]$Matches[1];ticks=400;minimumEntityTicks=[int]$Matches[2];tickets=[int]$Matches[3];elapsedMs=[long]$Matches[4];wallMspt=[double]$Matches[5];serverMspt=[double]$Matches[6]}}
  finally{if(!$process.HasExited){$process.Kill($true);$process.WaitForExit()};$stdout.GetAwaiter().GetResult()|Set-Content (Join-Path $artifact "$actors-stdout.log");$stderr.GetAwaiter().GetResult()|Set-Content (Join-Path $artifact "$actors-stderr.log");$process.Dispose()}
}
$commit=(& git -C $root rev-parse HEAD).Trim();$dirty=([bool](& git -C $root status --porcelain));$cpu=(Get-CimInstance Win32_Processor|Select-Object -First 1 -ExpandProperty Name);$ramGiB=[math]::Round((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory/1GB,1)
@{status='PASS';results=$results;artifact=$artifact;sourceCommit=$commit;sourceDirty=$dirty;cpu=$cpu;ramGiB=$ramGiB;os=[Environment]::OSVersion.VersionString;finishedUtc=[DateTime]::UtcNow.ToString('o')}|ConvertTo-Json -Depth 4|Set-Content (Join-Path $artifact 'result.json');Write-Output "AGENT_SCALING_PASS artifact=$artifact"
